name: Deploy App to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build artifact
        run: |
          cd app
          zip -r app.zip index.html health.html

      - name: Verify artifact
        run: ls -lah app/

      - name: Deploy to Azure (ZIP)
        uses: azure/webapps-deploy@v2
        with:
          app-name: app-mobilab-sandbox-8am3c
          package: app/app.zip